export const CAREER_LIST = {
  AGENT: { name:'Agent', desc: "Law enforcement agents, spies, corporate operatives and others who work in the shadows", id:1, qty:0, qualify:'INT6', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  AGENT_LAW_ENFORCEMENT: { name:'Agent Law Enforcement', desc: "Police officer or detective", id:2, qty:0, qualify:'INT6', survival:'END6', promotion:'INT6', parentId:1 },
  AGENT_INTELLIGENCE: { name:'Agent Intelligence', desc: "Spy or saboteur", id:3, qty:0, qualify:'INT6', survival:'INT7', promotion:'INT7', parentId:1 },
  AGENT_COPORATE: { name:'Agent Coporate', desc: "Corporate espionage", id:4, qty:0, qualify:'INT6', survival:'INT5', promotion:'INT5', parentId:1 },
  ARMY: { name:'Army', desc: "", id:5, qty:0, qualify:'END5', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  ARMY_SUPPORT: { name:'Army Support', desc: "", id:6, qty:0, qualify:'END5', survival:'END5', promotion:'END5', parentId:5 },
  ARMY_INFANTRY: { name:'Army Infantry', desc: "", id:7, qty:0, qualify:'END5', survival:'STR6', promotion:'STR6', parentId:5 },
  ARMY_CAVALRY: { name:'Army Cavalry', desc: "", id:8, qty:0, qualify:'END5', survival:'DEX7', promotion:'DEX7', parentId:5 },
  CITIZEN: { name:'Citizen', desc: "", id:9, qty:0, qualify:'EDU5', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  CITIZEN_CORPORATE: { name:'Citizen Corporate', desc: "", id:10, qty:0, qualify:'EDU5', survival:'SOC6', promotion:'INT6', parentId:9 },
  CITIZEN_WORKER: { name:'Citizen Worker', desc: "", id:11, qty:0, qualify:'EDU5', survival:'END4', promotion:'EDU8', parentId:9 },
  CITIZEN_COLONIST: { name:'Citizen Colonist', desc: "", id:12, qty:0, qualify:'EDU5', survival:'INT7', promotion:'END5', parentId:9 },
  DRIFTER: { name:'Drifter', desc: "", id:13, qty:0, qualify:'AUT0', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  DRIFTER_BARBARIAN: { name:'Drifter Barbarian', desc: "", id:14, qty:0, qualify:'AUT0', survival:'END7', promotion:'STR7', parentId:13 },
  DRIFTER_WANDERER: { name:'Drifter Wanderer', desc: "", id:15, qty:0, qualify:'AUT0', survival:'END7', promotion:'INT7', parentId:13 },
  DRIFTER_SCAVENGER: { name:'Drifter Scavenger', desc: "", id:16, qty:0, qualify:'AUT0', survival:'DEX7', promotion:'END7', parentId:13 },
  ENTERTAINER: { name:'Entertainer', desc: "", id:17, qty:0, qualify:'INT5', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  ENTERTAINER_ARTIST: { name:'Entertainer Artist', desc: "", id:18, qty:0, qualify:'INT5', survival:'SOC6', promotion:'INT6', parentId:17 },
  ENTERTAINER_JOURNALIST: { name:'Entertainer Journalist', desc: "", id:19, qty:0, qualify:'INT5', survival:'EDU7', promotion:'INT5', parentId:17 },
  ENTERTAINER_PERFORMER: { name:'Entertainer Performer', desc: "", id:20, qty:0, qualify:'INT5', survival:'INT5', promotion:'DEX7', parentId:17 },
  MARINES: { name:'Marines', desc: "", id:21, qty:0, qualify:'END6', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  MARINES_SUPPORT: { name:'Marines Support', desc: "", id:22, qty:0, qualify:'END6', survival:'END5', promotion:'EDU7', parentId:21 },
  MARINES_STAR_MARINE: { name:'Marines Star Marine', desc: "", id:23, qty:0, qualify:'END6', survival:'END6', promotion:'EDU6', parentId:21 },
  MARINES_GROUND_ASSAULT: { name:'Marines Ground Assault', desc: "", id:24, qty:0, qualify:'END6', survival:'END7', promotion:'EDU5', parentId:21 },
  MERCHANT: { name:'Merchant', desc: "", id:25, qty:0, qualify:'INT4', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  MERCHANT_MARINE: { name:'Merchant Marine', desc: "", id:26, qty:0, qualify:'INT4', survival:'EDU5', promotion:'INT7', parentId:25 },
  MERCHANT_FREE_TRADER: { name:'Merchant Free Trader', desc: "", id:27, qty:0, qualify:'INT4', survival:'DEX6', promotion:'INT6', parentId:25 },
  MERCHANT_BROKER: { name:'Merchant Broker', desc: "", id:28, qty:0, qualify:'INT4', survival:'EDU5', promotion:'INT7', parentId:25 },
  NAVY: { name:'Navy', desc: "", id:29, qty:0, qualify:'INT6', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  NAVY_CREW: { name:'Navy Crew', desc: "", id:30, qty:0, qualify:'INT6', survival:'INT5', promotion:'EDU7', parentId:29 },
  NAVY_ENGINEERING: { name:'Navy Engineering', desc: "", id:31, qty:0, qualify:'INT6', survival:'INT6', promotion:'EDU6', parentId:29 },
  NAVY_FLIGHT: { name:'Navy Flight', desc: "", id:32, qty:0, qualify:'INT6', survival:'DEX7', promotion:'EDU5', parentId:29 },
  NOBILITY: { name:'Nobility', desc: "", id:33, qty:0, qualify:'SOC10', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  NOBILITY_ADMINISTRATOR: { name:'Nobility Administrator', desc: "", id:34, qty:0, qualify:'SOC10', survival:'INT4', promotion:'EDU6', parentId:33 },
  NOBILITY_DIPLOMAT: { name:'Nobility Diplomat', desc: "", id:35, qty:0, qualify:'SOC10', survival:'INT5', promotion:'SOC7', parentId:33 },
  NOBILITY_DILETTANTE_: { name:'Nobility Dilettante ', desc: "", id:36, qty:0, qualify:'SOC10', survival:'SOC3', promotion:'INT8', parentId:33 },
  ROGUE: { name:'Rogue', desc: "", id:37, qty:0, qualify:'DEX6', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  ROGUE_THIEF: { name:'Rogue Thief', desc: "", id:38, qty:0, qualify:'DEX6', survival:'INT6', promotion:'DEX6', parentId:37 },
  ROGUE_ENFORCER: { name:'Rogue Enforcer', desc: "", id:39, qty:0, qualify:'DEX6', survival:'END6', promotion:'STR6', parentId:37 },
  ROGUE_PIRATE: { name:'Rogue Pirate', desc: "", id:40, qty:0, qualify:'DEX6', survival:'DEX6', promotion:'INT6', parentId:37 },
  SCHOLAR: { name:'Scholar', desc: "", id:41, qty:0, qualify:'INT6', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  SCHOLAR_FIELD_RESEARCHER: { name:'Scholar Field Researcher', desc: "", id:42, qty:0, qualify:'INT6', survival:'END6', promotion:'INT6', parentId:41 },
  SCHOLAR_SCIENTIST: { name:'Scholar Scientist', desc: "", id:43, qty:0, qualify:'INT6', survival:'EDU4', promotion:'INT8', parentId:41 },
  SCHOLAR_PHYSICIAN: { name:'Scholar Physician', desc: "", id:44, qty:0, qualify:'INT6', survival:'EDU4', promotion:'EDU8', parentId:41 },
  SCOUT: { name:'Scout', desc: "", id:45, qty:0, qualify:'INT5', survival:'FALSE', promotion:'FALSE', parentId:FALSE },
  SCOUT_COURIER: { name:'Scout Courier', desc: "", id:46, qty:0, qualify:'INT5', survival:'END5', promotion:'EDU9', parentId:45 },
  SCOUT_SURVEY: { name:'Scout Survey', desc: "", id:47, qty:0, qualify:'INT5', survival:'END6', promotion:'INT8', parentId:45 },
  SCOUT_EXPLORATION: { name:'Scout Exploration', desc: "", id:48, qty:0, qualify:'INT5', survival:'END7', promotion:'EDU7', parentId:45 }
};
