export const SKILL_LIST = {
  ADMIN: { name:'Admin', desc: "", id:1, qty:0 },
  ADVOCATE: { name:'Advocate', desc: "", id:2, qty:0 },
  ANIMALS: { name:'Animals', desc: "", id:3, qty:0 },
  ATHLETICS: { name:'Athletics', desc: "", id:4, qty:0 },
  ART: { name:'Art', desc: "", id:5, qty:0 },
  ASTROGATION: { name:'Astrogation', desc: "", id:6, qty:0 },
  BATTLE_DRESS: { name:'Battle Dress', desc: "", id:7, qty:0 },
  BROKER: { name:'Broker', desc: "", id:8, qty:0 },
  CAROUSE: { name:'Carouse', desc: "", id:9, qty:0 },
  COMMS: { name:'Comms', desc: "", id:10, qty:0 },
  COMPUTERS: { name:'Computers', desc: "", id:11, qty:0 },
  DECEPTION: { name:'Deception', desc: "", id:12, qty:0 },
  DIPLOMAT: { name:'Diplomat', desc: "", id:13, qty:0 },
  DRIVE: { name:'Drive', desc: "", id:14, qty:0 },
  ENGINEER: { name:'Engineer', desc: "", id:15, qty:0 },
  EXPLOSIVES: { name:'Explosives', desc: "", id:16, qty:0 },
  FLYER: { name:'Flyer', desc: "", id:17, qty:0 },
  GAMBLER: { name:'Gambler', desc: "", id:18, qty:0 },
  GUNNER: { name:'Gunner', desc: "", id:19, qty:0 },
  GUN_COMBAT: { name:'Gun Combat', desc: "", id:20, qty:0 },
  HEAVY_WEAPONS: { name:'Heavy Weapons', desc: "", id:21, qty:0 },
  INVESTIGATE: { name:'Investigate', desc: "", id:22, qty:0 },
  JACK_OF_ALL_TRADES: { name:'Jack of All Trades', desc: "", id:23, qty:0 },
  LANGUAGE: { name:'Language', desc: "", id:24, qty:0 },
  LEADERSHIP: { name:'Leadership', desc: "", id:25, qty:0 },
  MECHANIC: { name:'Mechanic', desc: "", id:26, qty:0 },
  MEDIC: { name:'Medic', desc: "", id:27, qty:0 },
  MELEE: { name:'Melee', desc: "", id:28, qty:0 },
  NAVIGATION: { name:'Navigation', desc: "", id:29, qty:0 },
  PERSUADE: { name:'Persuade', desc: "", id:30, qty:0 },
  PILOT: { name:'Pilot', desc: "", id:31, qty:0 },
  RECON: { name:'Recon', desc: "", id:32, qty:0 },
  REMOTE_OPERATIONS: { name:'Remote Operations', desc: "", id:33, qty:0 },
  SCIENCE: { name:'Science', desc: "", id:34, qty:0 },
  PHYSICAL_SCIENCES: { name:'Physical Sciences', desc: "", id:35, qty:0, parentId:34 },
  LIFE_SCIENCES: { name:'Life Sciences', desc: "", id:36, qty:0, parentId:34 },
  SOCIAL_SCIENCES: { name:'Social Sciences', desc: "", id:37, qty:0, parentId:34 },
  SPACE_SCIENCES: { name:'Space Sciences', desc: "", id:38, qty:0, parentId:34 },
  SEAFARER: { name:'Seafarer', desc: "", id:39, qty:0 },
  SENSORS: { name:'Sensors', desc: "", id:40, qty:0 },
  STEALTH: { name:'Stealth', desc: "", id:41, qty:0 },
  STEWARD: { name:'Steward', desc: "", id:42, qty:0 },
  STREETWISE: { name:'Streetwise', desc: "", id:43, qty:0 },
  SURVIVAL: { name:'Survival', desc: "", id:44, qty:0 },
  TACTICS: { name:'Tactics', desc: "", id:45, qty:0 },
  TRADE: { name:'Trade', desc: "", id:46, qty:0 },
  VACC_SUIT: { name:'Vacc Suit', desc: "", id:47, qty:0 },
  ZERO_G: { name:'Zero-G', desc: "", id:48, qty:0 },
  RIDING: { name:'Riding', desc: "", id:49, qty:0, parentId:3 },
  VETERINARY: { name:'Veterinary', desc: "", id:50, qty:0, parentId:3 },
  TRAINING: { name:'Training', desc: "", id:51, qty:0, parentId:3 },
  FARMING: { name:'Farming', desc: "", id:52, qty:0, parentId:3 },
  COORDINATION: { name:'Coordination', desc: "", id:53, qty:0, parentId:4 },
  ENDURANCE: { name:'Endurance', desc: "", id:54, qty:0, parentId:4 },
  STRENGTH: { name:'Strength', desc: "", id:55, qty:0, parentId:4 },
  FLYING: { name:'Flying', desc: "", id:56, qty:0, parentId:4 },
  ACTING: { name:'Acting', desc: "", id:57, qty:0, parentId:5 },
  DANCE: { name:'Dance', desc: "", id:58, qty:0, parentId:5 },
  HOLOGRAPHY: { name:'Holography', desc: "", id:59, qty:0, parentId:5 },
  INSTRUMENT: { name:'Instrument', desc: "", id:60, qty:0, parentId:5 },
  SCULPTING: { name:'Sculpting', desc: "", id:61, qty:0, parentId:5 },
  WRITING: { name:'Writing', desc: "", id:62, qty:0, parentId:5 },
  MOLE: { name:'Mole', desc: "", id:63, qty:0, parentId:14 },
  TRACKED: { name:'Tracked', desc: "", id:64, qty:0, parentId:14 },
  WHEELED: { name:'Wheeled', desc: "", id:65, qty:0, parentId:14 },
  MANOEUVRE_DRIVE_M_DRIVE: { name:'Manoeuvre Drive (M-Drive)', desc: "", id:66, qty:0, parentId:15 },
  JUMP_DRIVE_J_DRIVE: { name:'Jump Drive (J-Drive)', desc: "", id:67, qty:0, parentId:15 },
  ELECTRONICS: { name:'Electronics', desc: "", id:68, qty:0, parentId:15 },
  LIFE_SUPPORT: { name:'Life Support', desc: "", id:69, qty:0, parentId:15 },
  POWER: { name:'Power', desc: "", id:70, qty:0, parentId:15 },
  GRAV: { name:'Grav', desc: "", id:71, qty:0, parentId:17 },
  ROTOR: { name:'Rotor', desc: "", id:72, qty:0, parentId:17 },
  WING: { name:'Wing', desc: "", id:73, qty:0, parentId:17 },
  TURRETS: { name:'Turrets', desc: "", id:74, qty:0, parentId:19 },
  ORTILLERY: { name:'Ortillery', desc: "", id:75, qty:0, parentId:19 },
  SCREENS: { name:'Screens', desc: "", id:76, qty:0, parentId:19 },
  CAPITAL_WEAPONS: { name:'Capital Weapons', desc: "", id:77, qty:0, parentId:19 },
  SLUG_RIFLE: { name:'Slug Rifle', desc: "", id:78, qty:0, parentId:20 },
  SLUG_PISTOL: { name:'Slug Pistol', desc: "", id:79, qty:0, parentId:20 },
  SHOTGUN: { name:'Shotgun', desc: "", id:80, qty:0, parentId:20 },
  ENERGY_RIFLE: { name:'Energy Rifle', desc: "", id:81, qty:0, parentId:20 },
  ENERGY_PISTOL: { name:'Energy Pistol', desc: "", id:82, qty:0, parentId:20 },
  LAUNCHERS: { name:'Launchers', desc: "", id:83, qty:0, parentId:21 },
  MAN_PORTABLE_ARTILLERY: { name:'Man Portable Artillery', desc: "", id:84, qty:0, parentId:21 },
  FIELD_ARTILLERY: { name:'Field Artillery', desc: "", id:85, qty:0, parentId:21 },
  ANGLIC: { name:'Anglic', desc: "Common trade language of the Third Imperium", id:86, qty:0, parentId:24 },
  VILANI: { name:'Vilani', desc: "Language spoken by the Vilan of the First Imperium", id:87, qty:0, parentId:24 },
  ZDETI: { name:'Zdeti', desc: "Zhodani spoken language", id:88, qty:0, parentId:24 },
  OYNPRITH: { name:'Oynprith', desc: "Droyne ritual language", id:89, qty:0, parentId:24 },
  UNARMED_COMBAT: { name:'Unarmed Combat', desc: "", id:90, qty:0, parentId:28 },
  BLADE: { name:'Blade', desc: "", id:91, qty:0, parentId:28 },
  BLUDGEON: { name:'Bludgeon', desc: "", id:92, qty:0, parentId:28 },
  NATURAL_WEAPONS: { name:'Natural Weapons', desc: "", id:93, qty:0, parentId:28 },
  SMALL_CRAFT: { name:'Small Craft', desc: "", id:94, qty:0, parentId:31 },
  SPACECRAFT: { name:'Spacecraft', desc: "", id:95, qty:0, parentId:31 },
  CAPITAL_SHIPS: { name:'Capital Ships', desc: "", id:96, qty:0, parentId:31 },
  PHYSICS: { name:'Physics', desc: "", id:97, qty:0, parentId:35 },
  CHEMISTRY: { name:'Chemistry', desc: "", id:98, qty:0, parentId:35 },
  ELECTRONICS: { name:'Electronics', desc: "", id:99, qty:0, parentId:35 },
  BIOLOGY: { name:'Biology', desc: "", id:100, qty:0, parentId:36 },
  CYBERNETICS: { name:'Cybernetics', desc: "Study of blending living and synthetic life", id:101, qty:0, parentId:36 },
  GENETICS: { name:'Genetics', desc: "", id:102, qty:0, parentId:36 },
  PSIONICOLOGY: { name:'Psionicology', desc: "", id:103, qty:0, parentId:36 },
  ARCHEOLOGY: { name:'Archeology', desc: "", id:104, qty:0, parentId:37 },
  ECONOMICS: { name:'Economics', desc: "", id:105, qty:0, parentId:37 },
  HISTORY: { name:'History', desc: "", id:106, qty:0, parentId:37 },
  LINGUISTICS: { name:'Linguistics', desc: "", id:107, qty:0, parentId:37 },
  PHILOSOPHY: { name:'Philosophy', desc: "", id:108, qty:0, parentId:37 },
  PSYCHOLOGY: { name:'Psychology', desc: "Study of psionic powers and phenomena", id:109, qty:0, parentId:37 },
  SOPHONTOLOGY: { name:'Sophontology', desc: "Study of intelligent living creatures", id:110, qty:0, parentId:37 },
  PLANETOLOGY: { name:'Planetology', desc: "", id:111, qty:0, parentId:38 },
  ROBOTICS: { name:'Robotics', desc: "", id:112, qty:0, parentId:38 },
  XENOLOGY: { name:'Xenology', desc: "", id:113, qty:0, parentId:38 },
  SAIL: { name:'Sail', desc: "", id:114, qty:0, parentId:39 },
  SUBMARINE: { name:'Submarine', desc: "", id:115, qty:0, parentId:39 },
  OCEAN_SHIPS: { name:'Ocean Ships', desc: "", id:116, qty:0, parentId:39 },
  MOTORBOATS: { name:'Motorboats', desc: "", id:117, qty:0, parentId:39 },
  MILITARY_TACTICS: { name:'Military Tactics', desc: "", id:118, qty:0, parentId:45 },
  NAVAL_TACTICS: { name:'Naval Tactics', desc: "", id:119, qty:0, parentId:45 },
  BIOLOGICALS: { name:'Biologicals', desc: "", id:120, qty:0, parentId:46 },
  CIVIL_ENGINEERING: { name:'Civil Engineering', desc: "", id:121, qty:0, parentId:46 },
  SPACE_CONSTRUCTION: { name:'Space Construction', desc: "", id:122, qty:0, parentId:46 },
  HYDROPONICS: { name:'Hydroponics', desc: "", id:123, qty:0, parentId:46 },
  POLYMERS: { name:'Polymers', desc: "", id:124, qty:0, parentId:46 },
};

export const EDUCATION_SKILLS = [
  SKILL_LIST['ADMIN'],
  SKILL_LIST['ADVOCATE'],
  SKILL_LIST['ART'],
  SKILL_LIST['CAROUSE'],
  SKILL_LIST['COMMS'],
  SKILL_LIST['COMPUTERS'],
  SKILL_LIST['DRIVE'],
  SKILL_LIST['ENGINEER'],
  SKILL_LIST['LANGUAGE'],
  SKILL_LIST['MEDIC'],
  SKILL_LIST['PHYSICAL_SCIENCES'],
  SKILL_LIST['LIFE_SCIENCES'],
  SKILL_LIST['SOCIAL_SCIENCES'],
  SKILL_LIST['SPACE_SCIENCES'],
  SKILL_LIST['TRADE']
];
