import { CareerKeys, CareerObject } from "./types";
/** For some reason, all items have to be imported separately - perhaps a circular dependency? */
import { AGENT } from "./agent";
import { ARMY } from "./army";
import { CITIZEN } from "./citizen";
import { DRIFTER } from "./drifter";
import { ENTERTAINER } from "./entertainer";
import { MARINES } from "./marines";

export const CAREER_LIST: { [K in CareerKeys]?: CareerObject } = {
  AGENT,
  ARMY,
  CITIZEN,
  DRIFTER,
  ENTERTAINER,
  MARINES,
  // MERCHANT: {
  //   type: "CAREER",
  //   name: "Merchant",
  //   desc: "",
  //   id: 25,
  //   qty: 0,
  //   qualify: "INT4",
  //   survival: false,
  //   promotion: false,
  // },
  // MERCHANT_MARINE: {
  //   type: "CAREER",
  //   name: "Merchant Marine",
  //   desc: "",
  //   id: 26,
  //   qty: 0,
  //   qualify: "INT4",
  //   survival: "EDU5",
  //   promotion: "INT7",
  //   parentId: 25,
  // },
  // MERCHANT_FREE_TRADER: {
  //   type: "CAREER",
  //   name: "Merchant Free Trader",
  //   desc: "",
  //   id: 27,
  //   qty: 0,
  //   qualify: "INT4",
  //   survival: "DEX6",
  //   promotion: "INT6",
  //   parentId: 25,
  // },
  // MERCHANT_BROKER: {
  //   type: "CAREER",
  //   name: "Merchant Broker",
  //   desc: "",
  //   id: 28,
  //   qty: 0,
  //   qualify: "INT4",
  //   survival: "EDU5",
  //   promotion: "INT7",
  //   parentId: 25,
  // },
  // NAVY: {
  //   type: "CAREER",
  //   name: "Navy",
  //   desc: "",
  //   id: 29,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: false,
  //   promotion: false,
  // },
  // NAVY_CREW: {
  //   type: "CAREER",
  //   name: "Navy Crew",
  //   desc: "",
  //   id: 30,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "INT5",
  //   promotion: "EDU7",
  //   parentId: 29,
  // },
  // NAVY_ENGINEERING: {
  //   type: "CAREER",
  //   name: "Navy Engineering",
  //   desc: "",
  //   id: 31,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "INT6",
  //   promotion: "EDU6",
  //   parentId: 29,
  // },
  // NAVY_FLIGHT: {
  //   type: "CAREER",
  //   name: "Navy Flight",
  //   desc: "",
  //   id: 32,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "DEX7",
  //   promotion: "EDU5",
  //   parentId: 29,
  // },
  // NOBILITY: {
  //   type: "CAREER",
  //   name: "Nobility",
  //   desc: "",
  //   id: 33,
  //   qty: 0,
  //   qualify: "SOC10",
  //   survival: false,
  //   promotion: false,
  // },
  // NOBILITY_ADMINISTRATOR: {
  //   type: "CAREER",
  //   name: "Nobility Administrator",
  //   desc: "",
  //   id: 34,
  //   qty: 0,
  //   qualify: "SOC10",
  //   survival: "INT4",
  //   promotion: "EDU6",
  //   parentId: 33,
  // },
  // NOBILITY_DIPLOMAT: {
  //   type: "CAREER",
  //   name: "Nobility Diplomat",
  //   desc: "",
  //   id: 35,
  //   qty: 0,
  //   qualify: "SOC10",
  //   survival: "INT5",
  //   promotion: "SOC7",
  //   parentId: 33,
  // },
  // NOBILITY_DILETTANTE: {
  //   type: "CAREER",
  //   name: "Nobility Dilettante",
  //   desc: "",
  //   id: 36,
  //   qty: 0,
  //   qualify: "SOC10",
  //   survival: "SOC3",
  //   promotion: "INT8",
  //   parentId: 33,
  // },
  // ROGUE: {
  //   type: "CAREER",
  //   name: "Rogue",
  //   desc: "",
  //   id: 37,
  //   qty: 0,
  //   qualify: "DEX6",
  //   survival: false,
  //   promotion: false,
  // },
  // ROGUE_THIEF: {
  //   type: "CAREER",
  //   name: "Rogue Thief",
  //   desc: "",
  //   id: 38,
  //   qty: 0,
  //   qualify: "DEX6",
  //   survival: "INT6",
  //   promotion: "DEX6",
  //   parentId: 37,
  // },
  // ROGUE_ENFORCER: {
  //   type: "CAREER",
  //   name: "Rogue Enforcer",
  //   desc: "",
  //   id: 39,
  //   qty: 0,
  //   qualify: "DEX6",
  //   survival: "END6",
  //   promotion: "STR6",
  //   parentId: 37,
  // },
  // ROGUE_PIRATE: {
  //   type: "CAREER",
  //   name: "Rogue Pirate",
  //   desc: "",
  //   id: 40,
  //   qty: 0,
  //   qualify: "DEX6",
  //   survival: "DEX6",
  //   promotion: "INT6",
  //   parentId: 37,
  // },
  // SCHOLAR: {
  //   type: "CAREER",
  //   name: "Scholar",
  //   desc: "",
  //   id: 41,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: false,
  //   promotion: false,
  // },
  // SCHOLAR_FIELD_RESEARCHER: {
  //   type: "CAREER",
  //   name: "Scholar Field Researcher",
  //   desc: "",
  //   id: 42,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "END6",
  //   promotion: "INT6",
  //   parentId: 41,
  // },
  // SCHOLAR_SCIENTIST: {
  //   type: "CAREER",
  //   name: "Scholar Scientist",
  //   desc: "",
  //   id: 43,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "EDU4",
  //   promotion: "INT8",
  //   parentId: 41,
  // },
  // SCHOLAR_PHYSICIAN: {
  //   type: "CAREER",
  //   name: "Scholar Physician",
  //   desc: "",
  //   id: 44,
  //   qty: 0,
  //   qualify: "INT6",
  //   survival: "EDU4",
  //   promotion: "EDU8",
  //   parentId: 41,
  // },
  // SCOUT: {
  //   type: "CAREER",
  //   name: "Scout",
  //   desc: "",
  //   id: 45,
  //   qty: 0,
  //   qualify: "INT5",
  //   survival: false,
  //   promotion: false,
  // },
  // SCOUT_COURIER: {
  //   type: "CAREER",
  //   name: "Scout Courier",
  //   desc: "",
  //   id: 46,
  //   qty: 0,
  //   qualify: "INT5",
  //   survival: "END5",
  //   promotion: "EDU9",
  //   parentId: 45,
  // },
  // SCOUT_SURVEY: {
  //   type: "CAREER",
  //   name: "Scout Survey",
  //   desc: "",
  //   id: 47,
  //   qty: 0,
  //   qualify: "INT5",
  //   survival: "END6",
  //   promotion: "INT8",
  //   parentId: 45,
  // },
  // SCOUT_EXPLORATION: {
  //   type: "CAREER",
  //   name: "Scout Exploration",
  //   desc: "",
  //   id: 48,
  //   qty: 0,
  //   qualify: "INT5",
  //   survival: "END7",
  //   promotion: "EDU7",
  //   parentId: 45,
  // },
};
